import { StyleSheet, Platform } from "react-native";
import { BrandColors, BorderRadius, Spacing } from "../../shared/theme";

export const cardStyles = StyleSheet.create({
  standardCard: {
    backgroundColor: BrandColors.CARD,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: BrandColors.BORDER,
    padding: Spacing.base,
    marginBottom: Spacing.base,
    ...Platform.select({
      ios: {
        shadowColor: BrandColors.PRIMARY_BLUE_DARK,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.04,
        shadowRadius: 5,
      },
      android: {
        elevation: 2,
      },
      default: {},
    }),
  },
  flatCard: {
    backgroundColor: BrandColors.CARD,
    borderRadius: BorderRadius.base,
    borderWidth: 1,
    borderColor: BrandColors.BORDER,
    padding: Spacing.base,
    marginBottom: Spacing.md,
  },
  infoCardBlue: {
    backgroundColor: "#EFF6FF",
    borderRadius: BorderRadius.base,
    borderWidth: 1,
    borderColor: "#DBEAFE",
    padding: Spacing.md + 2,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: Spacing.base,
  },
  warningCardOrange: {
    backgroundColor: "#FFF7ED",
    borderRadius: BorderRadius.base,
    borderWidth: 1,
    borderColor: "#FFEDD5",
    padding: Spacing.md + 2,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: Spacing.base,
  },
  successCardGreen: {
    backgroundColor: "#F0FDF4",
    borderRadius: BorderRadius.base,
    borderWidth: 1,
    borderColor: "#DCFCE7",
    padding: Spacing.md + 2,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: Spacing.base,
  },
  iconCircleBlue: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#2563EB",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  iconCircleOrange: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: BrandColors.PRIMARY_ORANGE,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  iconCircleGreen: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#16A34A",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
});
